name: "2jciebu-exporter"
description: "Prometheus exporter for OMRON USB Environment Sensor 2JCIE-BU"
version: "0.0.0"
slug: "2jciebu_exporter"
init: false
url: "https://github.com/yasu-hide/2jciebu-prometheus/"
panel_icon: "mdi:thermometer"
startup: services
arch:
  - aarch64
  - amd64
options:
  SENSOR_SERIAL_DEVICE: "/dev/ttyUSB0"
  SERVER_HTTP_PORT: 8010
uart: true
udev: true
schema:
  SENSOR_SERIAL_DEVICE: device(subsystem=tty)?
  SERVER_HTTP_PORT: port?
