name: "nut_exporter"
description: "Network UPS Tools (NUT) Prometheus Exporter"
version: "0.0.0"
slug: "nut_exporter"
init: false
url: "https://github.com/druggeri/nut_exporter/"
panel_icon: "mdi:lightning-bolt"
startup: services
arch:
  - aarch64
  - amd64
options:
  NUT_EXPORTER_SERVER: "127.0.0.1"
  NUT_EXPORTER_SERVERPORT: 3493
  NUT_EXPORTER_USERNAME: ""
  NUT_EXPORTER_PASSWORD: ""
  NUT_EXPORTER_DISABLE_DEVICE_INFO: false
  NUT_EXPORTER_VARIABLES: "battery.charge,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,ups.load,ups.status"
  NUT_EXPORTER_ON_REGEX: "^(enable|enabled|on|true|active|activated)$"
  NUT_EXPORTER_OFF_REGEX: "^(disable|disabled|off|false|inactive|deactivated)$"
  NUT_EXPORTER_STATUSES: "OL,OB,LB,HB,RB,CHRG,DISCHRG,BYPASS,CAL,OFF,OVER,TRIM,BOOST,FSD,SD"
  NUT_EXPORTER_METRICS_NAMESPACE: "network_ups_tools"
  NUT_EXPORTER_WEB_SYSTEMD_SOCKET: false
  NUT_EXPORTER_WEB_LISTEN_ADDRESS: ":9199"
  NUT_EXPORTER_WEB_CONFIG_FILE: ""
  NUT_EXPORTER_WEB_TELEMETRY_PATH: "/ups_metrics"
  NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH: "/metrics"
  NUT_EXPORTER_PRINT_METRICS: false
  NUT_EXPORTER_LOG_LEVEL: "info"
  NUT_EXPORTER_LOG_JSON: false

schema:
  NUT_EXPORTER_SERVER: str
  NUT_EXPORTER_SERVERPORT: port
  NUT_EXPORTER_USERNAME: str?
  NUT_EXPORTER_PASSWORD: password?
  NUT_EXPORTER_DISABLE_DEVICE_INFO: bool
  NUT_EXPORTER_VARIABLES: str
  NUT_EXPORTER_ON_REGEX: str
  NUT_EXPORTER_OFF_REGEX: str
  NUT_EXPORTER_STATUSES: str
  NUT_EXPORTER_METRICS_NAMESPACE: str
  NUT_EXPORTER_WEB_SYSTEMD_SOCKET: bool
  NUT_EXPORTER_WEB_LISTEN_ADDRESS: str
  NUT_EXPORTER_WEB_CONFIG_FILE: str
  NUT_EXPORTER_WEB_TELEMETRY_PATH: str
  NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH: str
  NUT_EXPORTER_PRINT_METRICS: bool
  NUT_EXPORTER_LOG_LEVEL: list(error|warn|info|debug)
  NUT_EXPORTER_LOG_JSON: bool
