name: "nut_exporter"
description: "Network UPS Tools (NUT) Prometheus Exporter"
version: "0.0.0"
slug: "nut_exporter"
init: false
url: "https://github.com/druggeri/nut_exporter/"
panel_icon: "mdi:lightning-bolt"
startup: services
arch:
  - aarch64
  - amd64
options: {}
schema:
  NUT_EXPORTER_SERVER: str?
  NUT_EXPORTER_SERVERPORT: port?
  NUT_EXPORTER_USERNAME: str?
  NUT_EXPORTER_PASSWORD: password?
  NUT_EXPORTER_DISABLE_DEVICE_INFO: bool?
  NUT_EXPORTER_VARIABLES: str?
  NUT_EXPORTER_ON_REGEX: str?
  NUT_EXPORTER_OFF_REGEX: str?
  NUT_EXPORTER_STATUSES: str?
  NUT_EXPORTER_METRICS_NAMESPACE: str?
  NUT_EXPORTER_WEB_SYSTEMD_SOCKET: bool?
  NUT_EXPORTER_WEB_LISTEN_ADDRESS: str?
  NUT_EXPORTER_WEB_CONFIG_FILE: str?
  NUT_EXPORTER_WEB_TELEMETRY_PATH: str?
  NUT_EXPORTER_WEB_EXPORTER_TELEMETRY_PATH: str?
  NUT_EXPORTER_PRINT_METRICS: bool?
  NUT_EXPORTER_LOG_LEVEL: list(error|warn|info|debug)?
  NUT_EXPORTER_LOG_JSON: bool?
